CACHE MANIFEST
# VERSION 1.01.0070
# 1518570744
./audio/ambience/hq.mp3
./audio/dice.mp3
./audio/dice.ogg
./audio/key.mp3
./audio/key.ogg
./images/dice/d6_0.png
./images/dice/d6_1.png
./images/dice/d6_2.png
./images/dice/d6_3.png
./images/dice/d6_4.png
./images/dice/d6_5.png
./images/dice/d6_6.png
./images/factions/331.png
./images/factions/CBS.png
./images/factions/CCC.png
./images/factions/CCY.png
./images/factions/CDS.png
./images/factions/CFM.png
./images/factions/CGB.png
./images/factions/CGS.png
./images/factions/CHH.png
./images/factions/CJF.png
./images/factions/CM.png
./images/factions/CNC.png
./images/factions/CSA.png
./images/factions/CSC.png
./images/factions/CSJ.png
./images/factions/CSL.png
./images/factions/CSR.png
./images/factions/CSV.png
./images/factions/CSW.png
./images/factions/CW.png
./images/factions/CW2.png
./images/factions/CWV.png
./images/factions/DC.png
./images/factions/FS.png
./images/factions/SL.png
./images/factions/WD.png
./images/mechs/TBR.png
./images/pilots/m_053.png
./images/ranks/CW/01_Solahma.png
./images/ranks/CW/02_Cadet.png
./images/ranks/CW/03_PCom.png
./images/ranks/CW/04_SCom.png
./images/ranks/CW/05_SCapt.png
./images/ranks/CW/06_SCol.png
./images/ranks/CW/07_GCom.png
./images/ranks/CW/08_Khan.png
./images/ranks/CW/09_Lehrmeister.png
./images/body-bg_1.png
./images/body-bg_2.png
./images/body-bg_3.png
./images/body-bg_4.png
./images/bottom-bg.png
./images/bottom-left.png
./images/bt-logo.png
./images/icon_57x57.png
./images/icon_72x72.png
./images/icon_76x76.png
./images/icon_114x114.png
./images/icon_120x120.png
./images/icon_144x144.png
./images/icon_152x152.png
./images/icon_180x180.png
./images/icon_196x196.png
./images/mech_number.png
./images/top-right.png
./scripts/jquery-3.3.1.min.js
./scripts/cookies.js
./scripts/howler.min.js
./scripts/functions.js
./styles/font-awesome.min.css
./styles/styles.css
./favicon.png

NETWORK:
./db.php
./db_getdata.php
./index.html
./save.php
./unitselector.php
https://fonts.googleapis.com/css?family=Russo+One:400
https://fonts.googleapis.com/css?family=Pathway+Gothic+One:400
https://fonts.gstatic.com/stats/Pathway+Gothic+One/normal/400
https://fonts.gstatic.com/s/russoone/v6/Z9XUDmZRWg6M1LvRYsHOz8mJ.woff2
https://fonts.gstatic.com/s/pathwaygothicone/v6/MwQrbgD32-KAvjkYGNUUxAtW7pEBwx-tS1Zf.woff2
https://maxcdn.bootstrapcdn.com/favicon.ico
https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/fonts/fontawesome-webfont.woff?v=4.1.0
https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/fonts/fontawesome-webfont.ttf?v=4.1.0
*
